import { test,expect } from "@playwright/test";
import { mkdirSync } from "node:fs";
import { createServer } from "node:http";
import { fileURLToPath } from "node:url";
import { WebSocketServer } from "ws";
import { attachCodexRelay } from "../../src/codex-relay.mjs";

const auditDir=fileURLToPath(new URL("../../visual-audit/",import.meta.url));mkdirSync(auditDir,{recursive:true});
async function freePort(){const server=createServer();await new Promise((resolve,reject)=>server.listen(0,"127.0.0.1",resolve).once("error",reject));const port=server.address().port;await new Promise(resolve=>server.close(resolve));return port}

test("Codex plugin discovery exposes native search, details, skill contents and reconcile",async({page})=>{
  test.setTimeout(35_000);
  const thread={id:"plugin-fixture",name:"Plugin fixture",preview:"Native plugin discovery",cwd:process.cwd(),createdAt:Date.now()-1000,updatedAt:Date.now(),turns:[]};
  let installed=false,appCallable=true,mcpReady=false,rateUsed=12,account=null,notificationSocket=null;const calls=[];
  const summary=()=>({id:"weather@official",remotePluginId:"remote-weather",version:"1.2.3",localVersion:installed?"1.2.3":null,name:"weather",source:{type:"remote"},installed,enabled:true,availability:"available",interface:{displayName:"Weather Wizard",shortDescription:"Forecast tools",longDescription:"Search forecasts and weather alerts before installing.",developerName:"Trebell Labs",capabilities:["forecast","alerts"]},keywords:["weather"]});
  const upstreamHttp=createServer();const upstreamWss=new WebSocketServer({noServer:true});const sockets=new Set();
  upstreamHttp.on("upgrade",(req,socket,head)=>upstreamWss.handleUpgrade(req,socket,head,ws=>upstreamWss.emit("connection",ws,req)));
  upstreamWss.on("connection",ws=>{
    sockets.add(ws);notificationSocket=ws;ws.on("close",()=>sockets.delete(ws));
    ws.on("message",data=>{
      const message=JSON.parse(String(data));if(message.id==null||!message.method)return;calls.push(message);let result={};
      const respond=value=>ws.send(JSON.stringify({id:message.id,result:value}));
      if(message.method==="initialize")result={userAgent:"plugin-fixture"};
      else if(message.method==="thread/list")result={data:[thread],nextCursor:null};
      else if(message.method==="thread/loaded/list")result={data:[thread.id,"background-loaded-thread"],nextCursor:null};
      else if(message.method==="threadSection/list")result={data:[],nextCursor:null};
      else if(message.method==="thread/resume"||message.method==="thread/read")result={thread};
      else if(message.method==="thread/goal/get")result={goal:null};
      else if(message.method==="thread/attachment/list"||message.method==="thread/queue/list"||message.method==="thread/items/list")result={data:[],nextCursor:null};
      else if(message.method==="thread/runtimeInstances/list")result={supported:false,currentInstanceId:null,items:[]};
      else if(message.method==="skills/list")result={data:[]};
      else if(message.method==="plugin/list")result={marketplaces:installed?[{name:"official",path:null,plugins:[summary()]}]:[],marketplaceLoadErrors:[],featuredPluginIds:[]};
      else if(message.method==="plugin/search")result={data:[{plugin:summary(),marketplaceName:"official",marketplacePath:null}],nextCursor:null};
      else if(message.method==="plugin/read")result={plugin:{marketplaceName:"official",marketplacePath:null,summary:summary(),shareUrl:null,description:"A full weather plugin used to verify discovery.",skills:[{name:"forecast",description:"Forecast skill",shortDescription:"Get the forecast",interface:{displayName:"Forecast skill",shortDescription:"Get the forecast"},path:null,enabled:true}],onboardingSkill:null,hooks:[{key:"weather-hook",eventName:"sessionStart"}],apps:[{id:"weather-app",name:"Weather app"}],appTemplates:[],mcpServers:["weather-mcp"],scheduledTasks:[{key:"daily-weather",name:"Daily weather",prompt:"Check weather",schedule:{type:"daily",time:"08:00"}}]}};
      else if(message.method==="plugin/skill/read")result={contents:"# Forecast skill\nUse the weather tools to check forecasts."};
      else if(message.method==="plugin/install"){installed=true;respond({});return}
      else if(message.method==="plugin/uninstall"){installed=false;respond({});return}
      else if(message.method==="plugin/reconcile")result={changedPlugins:[{id:"weather@official",hasMcps:true,hasApps:true,hasHooks:true,hasSkills:true}],failedRemotePluginIds:[],failedMaterializationRemotePluginIds:[]};
      else if(message.method==="server/diagnostics")result={process:{id:4242,residentMemoryBytes:268435456,physicalFootprintBytes:314572800},gauges:[{name:"app.requests.in_flight",value:1},{name:"core.threads.live",value:3},{name:"core.turns.active",value:1},{name:"mcp.connections.live",value:2}]};
      else if(message.method==="app/list")result={data:[{id:"weather-app",name:"Weather app",description:"Weather connector runtime fixture",distributionChannel:"plugin",installUrl:null,isAccessible:true,isEnabled:true,pluginDisplayNames:["Weather Wizard"]}],nextCursor:null};
      else if(message.method==="app/installed")result={apps:[{id:"weather-app",runtimeName:"Weather app",enabled:true,callable:appCallable}]};
      else if(message.method==="app/read")result={apps:[{id:"weather-app",name:"Weather app",description:"Weather connector runtime fixture",distributionChannel:"plugin",installUrl:null,pluginDisplayNames:["Weather Wizard"],toolSummaries:[{name:"forecast",title:"Forecast",description:"Read the forecast",isEnabled:true,disabledReason:null,isReadOnly:true}]}],missingAppIds:[]};
      else if(message.method==="experimentalFeature/list")result={data:[{name:"step_model_switching",stage:"underDevelopment",displayName:"Step model switching",description:"Switch models between steps of a running turn.",announcement:null,enabled:false,defaultEnabled:false}],nextCursor:null};
      else if(message.method==="experimentalFeature/enablement/set")result={enablement:{}};
      else if(message.method==="mcpServerStatus/list")result={data:[{name:"weather-mcp",runtimeStatus:mcpReady?"connected":"starting",pluginId:"weather@official",serverInfo:null,serverCapabilities:null,tools:{},toolsError:null,resources:[],resourceTemplates:[],authStatus:mcpReady?"oauth":"notLoggedIn"}],nextCursor:null};
      else if(message.method==="hooks/list")result={data:[{cwd:process.cwd(),hooks:[{name:"session-check",event:"beforeTurn"}]}]};
      else if(message.method==="permissionProfile/list"||message.method==="plugin/share/list")result={data:[]};
      else if(message.method==="modelProvider/capabilities/read")result={namespaceTools:true,webSearch:true,imageGeneration:false};
      else if(message.method==="account/read")result={account,requiresOpenaiAuth:false};
      else if(message.method==="account/rateLimits/read")result={rateLimits:{primary:{usedPercent:rateUsed}}};
      else if(message.method==="account/usage/read")result={};
      else if(message.method==="config/read")result={config:{},layers:[]};
      else if(message.method==="configRequirements/read")result={requirements:{}};
      else if(message.method==="memory/status")result={v2ConsolidatedThreads:20,v2Ready:true};
      else if(message.method==="thread/unsubscribe")result={status:"unsubscribed"};
      respond(result);
    });
  });
  const upstreamPort=await freePort();await new Promise((resolve,reject)=>upstreamHttp.listen(upstreamPort,"127.0.0.1",resolve).once("error",reject));
  const relayHttp=createServer((_req,res)=>{res.writeHead(404);res.end()});const relay=attachCodexRelay(relayHttp,{targetUrl:`ws://127.0.0.1:${upstreamPort}`});
  const relayPort=await freePort();await new Promise((resolve,reject)=>relayHttp.listen(relayPort,"127.0.0.1",resolve).once("error",reject));
  try{
    await page.route(/\/api\/bootstrap$/,route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({mock:false,loggedIn:true,provider:"freebuff",providerReady:true,agentRuntime:"codex",agentRuntimeReady:true,appServerReady:true,wsUrl:`ws://127.0.0.1:${relayPort}/api/codex/ws`,cwd:process.cwd(),platform:"linux",version:"plugin-fixture",activeEnvironmentId:null,activeEnvironment:null})}));
    await page.route(/\/api\/state$/,route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({settings:{onboardingComplete:true,appearance:"dark",appearanceMode:"dark",panelAnimationMs:0,agentRuntime:"codex",agentRuntimeInstanceId:"codex-default",modelProvider:"freebuff",defaultPermissionMode:"supervised",defaultWorkspaceMode:"current"},projects:[],threadMeta:{[thread.id]:{projectless:true,environmentId:null}}})}));
    await page.route(/\/api\/models$/,route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({models:["freebuff/test/coding-fast"],metadata:{provider:"freebuff",models:[{id:"freebuff/test/coding-fast",name:"Coding Fast",provider:"freebuff",agent:"Codex"}]}})}));
    await page.route(/\/api\/projects$/,route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({projects:[]})}));
    await page.route(/\/api\/environment\/themes$/,route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({environmentKey:"local",environmentName:"Local machine",directory:"",themes:[]})}));
    await page.route(/\/api\/recovery$/,route=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify({enabled:false,items:[]})}));
    await page.goto("/");await page.getByRole("button",{name:/Plugin fixture/}).click();await page.getByRole("button",{name:"Tools",exact:true}).click();
    const diagnostics=page.locator(".capability-card").filter({hasText:"Codex runtime health"});await expect(diagnostics).toContainText("PID 4242");await expect(diagnostics).toContainText("256 MB");await expect(diagnostics).toContainText("Loaded sessions");await expect(diagnostics).toContainText("2");await expect(diagnostics).toContainText("Live threads");await expect(diagnostics).toContainText("3");
    expect(calls.some(call=>call.method==="server/diagnostics")).toBe(true);expect(calls.find(call=>call.method==="thread/loaded/list")?.params).toEqual({limit:100});
    await page.setViewportSize({width:1280,height:800});await diagnostics.scrollIntoViewIfNeeded();await page.screenshot({path:auditDir+"tools-runtime-health-1280x800.png",fullPage:false});
    await page.evaluate(()=>{document.documentElement.dataset.mode="light"});await page.screenshot({path:auditDir+"tools-runtime-health-light-1280x800.png",fullPage:false});
    await page.evaluate(()=>{document.documentElement.dataset.mode="dark"});await page.setViewportSize({width:1600,height:980});
    const appsCard=page.locator(".capability-card").filter({has:page.getByText("Apps / connectors",{exact:true})}).first();await appsCard.scrollIntoViewIfNeeded();await expect(appsCard).toContainText("1 installed · 1 callable now");await expect(appsCard).toContainText("callable");
    const installedCall=calls.find(call=>call.method==="app/installed"&&call.params?.forceRefresh===false);expect(installedCall?.params).toEqual({threadId:thread.id,forceRefresh:false});
    await appsCard.getByRole("button",{name:"Refresh runtime"}).click();await expect.poll(()=>calls.filter(call=>call.method==="app/installed"&&call.params?.forceRefresh===true).length).toBe(1);
    await page.setViewportSize({width:1280,height:800});await page.screenshot({path:auditDir+"tools-app-runtime-1280x800.png",fullPage:false});await page.evaluate(()=>{document.documentElement.dataset.mode="light"});await page.screenshot({path:auditDir+"tools-app-runtime-light-1280x800.png",fullPage:false});await page.evaluate(()=>{document.documentElement.dataset.mode="dark"});await page.setViewportSize({width:1600,height:980});
    const diagnosticsCallsBefore=calls.filter(call=>call.method==="server/diagnostics").length;
    const installedCallsBefore=calls.filter(call=>call.method==="app/installed"&&call.params?.forceRefresh===false).length;
    const mcpCallsBefore=calls.filter(call=>call.method==="mcpServerStatus/list").length;
    const rateCallsBefore=calls.filter(call=>call.method==="account/rateLimits/read").length;
    appCallable=false;mcpReady=true;rateUsed=44;
    notificationSocket.send(JSON.stringify({method:"app/list/updated",params:{data:[{id:"weather-app",name:"Weather app live",description:"Updated from Codex notification",distributionChannel:"plugin",installUrl:null,isAccessible:true,isEnabled:true,pluginDisplayNames:["Weather Wizard"]}]}}));
    notificationSocket.send(JSON.stringify({method:"mcpServer/startupStatus/updated",params:{threadId:thread.id,name:"weather-mcp",status:"ready",error:null,failureReason:null}}));
    notificationSocket.send(JSON.stringify({method:"account/rateLimits/updated",params:{rateLimits:{primary:{usedPercent:44}}}}));
    account={type:"chatgpt",email:"live@example.com",planType:"pro"};
    notificationSocket.send(JSON.stringify({method:"account/updated",params:{authMode:"chatgpt",planType:"pro"}}));
    notificationSocket.send(JSON.stringify({method:"modelProvider/authRecoveryStarted",params:{threadId:thread.id,turnId:"turn-live",provider:"freebuff",message:"Refreshing provider credentials"}}));
    notificationSocket.send(JSON.stringify({method:"model/rerouted",params:{threadId:thread.id,turnId:"turn-live",fromModel:"freebuff/test/coding-fast",toModel:"freebuff/test/coding-safe",reason:"highRiskCyberActivity"}}));
    notificationSocket.send(JSON.stringify({method:"model/safetyBuffering/updated",params:{threadId:thread.id,turnId:"turn-live",model:"freebuff/test/coding-safe",useCases:["cyber"],reasons:["userRisk"],showBufferingUi:true,fasterModel:"freebuff/test/coding-fast"}}));
    notificationSocket.send(JSON.stringify({method:"model/verification",params:{threadId:thread.id,turnId:"turn-live",verifications:["trustedAccessForCyber"]}}));
    notificationSocket.send(JSON.stringify({method:"configWarning",params:{summary:"Invalid hook timeout",details:"Expected a positive duration.",path:process.cwd()+"/.codex/config.toml",range:null}}));
    const hookRun={id:"hook-run-1",eventName:"beforeTurn",handlerType:"command",executionMode:"blocking",scope:"project",sourcePath:process.cwd()+"/.codex/hooks/session-check",source:"project",displayOrder:0,status:"running",statusMessage:"Checking workspace",startedAt:Date.now(),completedAt:null,durationMs:null,entries:[]};
    notificationSocket.send(JSON.stringify({method:"hook/started",params:{threadId:thread.id,turnId:"turn-live",run:hookRun}}));
    notificationSocket.send(JSON.stringify({method:"hook/completed",params:{threadId:thread.id,turnId:"turn-live",run:{...hookRun,status:"completed",statusMessage:"Lint checks passed",completedAt:Date.now()+42,durationMs:42}}}));
    await expect(appsCard).toContainText("Weather app live");await expect(appsCard).toContainText("installed");await expect(appsCard).toContainText("1 installed · 0 callable now");
    const mcpCard=page.locator(".capability-card").filter({has:page.getByText("MCP servers",{exact:true})}).first();await expect(mcpCard).toContainText("connected");await expect(mcpCard).toContainText("oauth");
    const accountCard=page.locator(".capability-card").filter({has:page.getByText("Account & usage",{exact:true})}).first();await expect(accountCard).toContainText("44%");await expect(accountCard).toContainText("live@example.com");await expect(accountCard).toContainText("Recovering freebuff authentication");
    notificationSocket.send(JSON.stringify({method:"modelProvider/authRecoveryCompleted",params:{threadId:thread.id,turnId:"turn-live",provider:"freebuff",message:"Provider credentials recovered"}}));
    await expect(accountCard).toContainText("Recovered freebuff authentication: Provider credentials recovered");
    await page.setViewportSize({width:1280,height:800});await accountCard.scrollIntoViewIfNeeded();await page.screenshot({path:auditDir+"tools-auth-recovery-1280x800.png",fullPage:false});
    await page.evaluate(()=>{document.documentElement.dataset.mode="light"});await page.screenshot({path:auditDir+"tools-auth-recovery-light-1280x800.png",fullPage:false});await page.evaluate(()=>{document.documentElement.dataset.mode="dark"});await page.setViewportSize({width:1600,height:980});
    const configCard=page.locator(".capability-card").filter({has:page.getByText("Configuration layers",{exact:true})}).first();await expect(configCard).toContainText("Invalid hook timeout");await expect(configCard).toContainText("Expected a positive duration.");
    const hooksCard=page.locator(".capability-card").filter({has:page.getByText("Hooks",{exact:true})}).first();await expect(hooksCard).toContainText("beforeTurn");await expect(hooksCard).toContainText("Lint checks passed");await expect(hooksCard).toContainText("42 ms");
    const providerCard=page.locator(".capability-card").filter({has:page.getByText("Provider capabilities",{exact:true})}).first();await expect(providerCard).toContainText("Model access verified");await providerCard.getByText(/Recent model routing & safety/).click();await expect(providerCard).toContainText("freebuff/test/coding-fast → freebuff/test/coding-safe");await expect(providerCard).toContainText("highRiskCyberActivity");await expect(providerCard).toContainText("safety buffering active");
    await expect.poll(()=>calls.filter(call=>call.method==="app/installed"&&call.params?.forceRefresh===false).length).toBeGreaterThan(installedCallsBefore);
    await expect.poll(()=>calls.filter(call=>call.method==="mcpServerStatus/list").length).toBeGreaterThan(mcpCallsBefore);
    await expect.poll(()=>calls.filter(call=>call.method==="account/rateLimits/read").length).toBeGreaterThan(rateCallsBefore);
    expect(calls.filter(call=>call.method==="server/diagnostics").length).toBe(diagnosticsCallsBefore);
    await page.setViewportSize({width:1280,height:800});await appsCard.scrollIntoViewIfNeeded();await page.screenshot({path:auditDir+"tools-live-native-refresh-1280x800.png",fullPage:false});
    await page.evaluate(()=>{document.documentElement.dataset.mode="light"});await mcpCard.scrollIntoViewIfNeeded();await page.screenshot({path:auditDir+"tools-live-native-refresh-light-1280x800.png",fullPage:false});await page.evaluate(()=>{document.documentElement.dataset.mode="dark"});await page.setViewportSize({width:1600,height:980});
    await page.setViewportSize({width:1280,height:800});await hooksCard.scrollIntoViewIfNeeded();await page.screenshot({path:auditDir+"tools-live-warnings-hooks-1280x800.png",fullPage:false});await page.evaluate(()=>{document.documentElement.dataset.mode="light"});await configCard.scrollIntoViewIfNeeded();await page.screenshot({path:auditDir+"tools-live-warnings-hooks-light-1280x800.png",fullPage:false});await page.evaluate(()=>{document.documentElement.dataset.mode="dark"});await page.setViewportSize({width:1600,height:980});
    await page.setViewportSize({width:1280,height:800});await providerCard.scrollIntoViewIfNeeded();await page.screenshot({path:auditDir+"tools-model-routing-1280x800.png",fullPage:false});await page.evaluate(()=>{document.documentElement.dataset.mode="light"});await page.screenshot({path:auditDir+"tools-model-routing-light-1280x800.png",fullPage:false});await page.evaluate(()=>{document.documentElement.dataset.mode="dark"});await page.setViewportSize({width:1600,height:980});
    const featureCard=page.locator(".capability-card").filter({has:page.getByText("Experimental features",{exact:true})}).first();await featureCard.scrollIntoViewIfNeeded();await featureCard.getByRole("button",{name:"Off"}).click();
    await expect(featureCard).toContainText("step_model_switching is read-only through the app-server.");
    expect(calls.some(call=>call.method==="experimentalFeature/enablement/set")).toBe(true);
    await page.setViewportSize({width:1280,height:800});await page.screenshot({path:auditDir+"tools-readonly-feature-1280x800.png",fullPage:false});await page.evaluate(()=>{document.documentElement.dataset.mode="light"});await page.screenshot({path:auditDir+"tools-readonly-feature-light-1280x800.png",fullPage:false});await page.evaluate(()=>{document.documentElement.dataset.mode="dark"});await page.setViewportSize({width:1600,height:980});
    const card=page.locator(".capability-card").filter({has:page.getByText("Plugins",{exact:true})}).first();const search=card.getByPlaceholder("Search plugin catalog");await search.fill("weather");await card.getByRole("button",{name:"Search",exact:true}).click();
    await expect(card).toContainText("Weather Wizard");const searchCall=calls.find(call=>call.method==="plugin/search");expect(searchCall?.params).toEqual({searchTerm:"weather",scope:"global",cwds:[process.cwd()],cursor:null,limit:20});
    const resultRow=card.locator(".plugin-search-results>div").filter({hasText:"Weather Wizard"});await resultRow.getByRole("button",{name:"Details"}).click();
    await expect(card).toContainText("Trebell Labs");await expect(card).toContainText("1 skills");await expect(card).toContainText("1 scheduled tasks");
    const detailCall=calls.find(call=>call.method==="plugin/read");expect(detailCall?.params).toEqual({marketplacePath:null,remoteMarketplaceName:"official",pluginName:"weather"});
    await card.getByRole("button",{name:"Read skill"}).click();await expect(card).toContainText("Use the weather tools to check forecasts.");
    expect(calls.find(call=>call.method==="plugin/skill/read")?.params).toEqual({remoteMarketplaceName:"official",remotePluginId:"remote-weather",skillName:"forecast"});
    await resultRow.getByRole("button",{name:"Install"}).click();await expect(resultRow.getByRole("button",{name:"Uninstall"})).toBeVisible();
    const installCall=calls.find(call=>call.method==="plugin/install");expect(installCall?.params?.pluginName).toBe("weather");expect(installCall?.params?.remoteMarketplaceName).toBe("official");expect(installCall?.params?.marketplacePath).toBeNull();expect(installCall?.params?.installAttemptId).toBeTruthy();
    await card.getByRole("button",{name:"Reconcile"}).click();await expect(card).toContainText("1 plugin change reconciled.");expect(calls.some(call=>call.method==="plugin/reconcile"&&call.params?.reason==="trebell-tools-refresh")).toBe(true);
    await page.screenshot({path:auditDir+"tools-plugin-discovery-1600x980.png",fullPage:true});
    await page.setViewportSize({width:1280,height:800});const overflow=await card.evaluate(node=>({client:node.clientWidth,scroll:node.scrollWidth}));expect(overflow.scroll).toBeLessThanOrEqual(overflow.client+1);await page.screenshot({path:auditDir+"tools-plugin-discovery-1280x800.png",fullPage:true});
    await page.evaluate(()=>{document.documentElement.dataset.mode="light"});await page.screenshot({path:auditDir+"tools-plugin-discovery-light-1280x800.png",fullPage:true});
  }finally{relay.close();for(const socket of sockets)try{socket.terminate()}catch{}upstreamWss.close();await Promise.all([new Promise(resolve=>relayHttp.close(resolve)),new Promise(resolve=>upstreamHttp.close(resolve))])}
});
